language: cpp

# TODO: caching for apt and also for PIN downloads
# sadly only available in travis private

before_install:
  - ./scripts/travis-ci/install_deps.sh
  - ./setup_pin.sh

install:
  - ./scripts/travis-ci/build.sh

script:
  - ./scripts/travis-ci/runtest.sh

notifications:
  email:
    recipients:
      - blair.strang@gmail.com

    on_success: always
    on_failure: always

os:
#  - linux
  - osx
 
